/**
 * Business domain error codes for i18n and exception handling.
 */

export const BUSINESS_ERROR_CODES = {
  VALIDATION_NAME_REQUIRED: 'BUSINESS_VALIDATION_NAME_REQUIRED',
  VALIDATION_HOURS_DAY: 'BUSINESS_VALIDATION_HOURS_DAY',
  VALIDATION_HOURS_TIME_FORMAT: 'BUSINESS_VALIDATION_HOURS_TIME_FORMAT',
  VALIDATION_HOURS_CLOSE_AFTER_OPEN:
    'BUSINESS_VALIDATION_HOURS_CLOSE_AFTER_OPEN',
  VALIDATION_HOURS_DUPLICATE_DAY: 'BUSINESS_VALIDATION_HOURS_DUPLICATE_DAY',
  VALIDATION_COORDINATES: 'BUSINESS_VALIDATION_COORDINATES',
  VALIDATION_FILE_TYPE: 'BUSINESS_VALIDATION_FILE_TYPE',
  VALIDATION_FILE_SIZE: 'BUSINESS_VALIDATION_FILE_SIZE',
  OWNER_REQUIRED: 'BUSINESS_OWNER_REQUIRED',
  NOT_FOUND: 'BUSINESS_NOT_FOUND',
} as const;
